[package]
name = "rs-uptobox"
version = "0.1.0"
edition = "2021"

[dependencies]
json-patch = "0.3.0"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
